[
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
     {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
     {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
     {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
     {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
    {'Brand':'Suzuki', 'CarName':'Swift'}
]